DATA:
    PATH: data
    DOWNLOAD: true
    FEWSHOT: 1000
    SHORT_DATASET_NAME: CtoS #AtoW
    LONG_DATASET_NAME: CCIC to SDNET #Amazon to Webcam
    DATASET_GROUP: concrete #office31
    WEIGHT_TYPE: natural
    SIZE_TYPE: source
    SOURCE: ccic #amazon
    TARGET: sdnet #webcam
    VAL_SPLIT_RATIO: 0.2

MODEL:
    NAME: resnet50
    NUM_CLASSES: 2 #31

PARAMS:
    BATCH_SIZE: 32
    LR: 1e-3
    LAMBDA: 1.0
    
GENERAL:
    FREEZE: true
    SEED: 253
    GPUS:
    - 2
    EPOCH: 20
    DEBUG: false
    NUM_WORKERS: 8
    
CALLBACKS:
    MODEL_CHECKPOINT:
        PARAMS:
            save_weights_only: false
            save_top_k: 1
            monitor: val_loss
            verbose: true
            mode: min
    EARLY_STOPPING:
        FLAG: false
        PARAMS:
            monitor: val_loss
            min_delta: 0.00
            patience: 3
            verbose: true